Sprint 3
EugeniaShimak/middle.messenger.praktikum.yandex pull request #3
Opened 2021-12-28 17:21 UTC by EugeniaShimak

…ers, store, routing, tests

2021-12-30 11:35 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, все выглядит отлично, но кажется есть некоторое непонимание в том, как работать с асинхроньщинной)

https://learn.javascript.ru/async - попробуйте перечитать эту статью и избавиться от лишнего в коде (в остальном работа отличная)

2021-12-30 11:35 UTC, DmitryKhitrin commented on .mocharc.json
> +}
[EOF](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

https://eslint.org/docs/rules/eol-last

2021-12-30 11:35 UTC, DmitryKhitrin commented on babel.config.js
> +};
EOF

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/api/Authorization.api.ts
> +}
EOF

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/api/User.api.ts
> +    static async changeUserProfile(userInfo: IUserInfo) {
Async нужен только если внутри используется await, во всех остальных случаях - это просто обычная функция возвращающая Promise

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/controllers/Auth.controller.ts
> +    }
async не нужен, для того что бы он был полезен, надо написать вот так:

```suggestion
    public async getUser() {
        try {
            const user = await AuthorizationAPI.getUser();
            this.store.setState({user});
            return user;
        } catch (e) {
            errorHandler(e);
        }
    }
```

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/controllers/Chats.controller.ts
> +        const users = await this.userController.getUserByLogin(userLogin);
- лучше выбрать один стул, либо просто Promise либо async await);
- все конструкции с await хорошо бы оборачивать в try{}catch, что бы не пропустить асинхронных ошибок;

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/controllers/Chats.controller.ts
> +        if (idChat === undefined) {
tyr{}catch

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/controllers/Chats.controller.ts
> +    public async connectWithChat(chatId: string | number) {
Я бы предложил разделить логику на два класса, один отвечает за создание сокет соединения и управления им, второй за непосредственно бизнес логику и работу с чатом

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/controllers/User.controller.ts
> +                            // @ts-ignore
Лучше написать корректный тип, а не использовать ts-ignore

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/controllers/User.controller.ts
> +    public async changeUserProfile({first_name, second_name, display_name, login, email, phone}: IUserInfo) {
тут не нужен async

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/controllers/User.controller.ts
> +        };
Зачем так?), почему нельзя:

```suggestion
    public async changeUserProfile(userInfo: IUserInfo) {
```

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/controllers/User.controller.ts
> +    public async getUserByLogin(login: string) {
async не нужен

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/utils/mydash/isObject.ts
> +}
EOF

2021-12-30 11:35 UTC, DmitryKhitrin commented on src/utils/router/Router.ts
> +        if (!route) {
👍

2022-01-06 21:35 UTC, EugeniaShimak commented on src/api/User.api.ts
> +    static async changeUserProfile(userInfo: IUserInfo) {
Да, что-то напутала под конец и уже везде его напихала, сейчас пофиксила, вроде все ок должно быть)

2022-01-07 07:40 UTC, DmitryKhitrin approved these changes
Спасибо за внесенные правки и удачи в следующем спринте!)

2022-01-07 07:40 UTC, DmitryKhitrin commented on src/controllers/Socket.controller.ts
> +        if (idChat !== undefined) {
Лучше не модифицировать таким образом аргументы функции, а создать новую переменную:

```
public async getChatID(initialChatId?: TIdChat) {
    const chatID = initialChatId === undefined ? getCookie('idChat') : initialChatId;
    
    // остальная логика
}
```

Это паттерн называется ранний вы

2022-01-07 07:40 UTC, DmitryKhitrin commented on src/utils/services/Block.ts
> +            if (response) {
Если ответа не будет, в данном случае не надо выбросить ошибку?

2022-01-07 23:35 UTC, EugeniaShimak commented on src/utils/services/Block.ts
> +            if (response) {
Не, там смысл в том, что если он положительный пришел, то надо вызвать ререндер компонента, а в остальных случаях (если вдруг не пришел) можно ничего не делать)

2022-01-07 23:42 UTC, EugeniaShimak commented on src/controllers/Socket.controller.ts
> +        if (idChat !== undefined) {
Спасибо за ревью!

2022-01-30 15:28 UTC, merged